In [1]:
[[123,12,23,34,54],[12,23,43,54,66],[77,45,23,12,43]]

[[123, 12, 23, 34, 54], [12, 23, 43, 54, 66], [77, 45, 23, 12, 43]]

In [4]:
import numpy
n = numpy.arange(27)

In [8]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
m = numpy.asarray([[123,12,23,34,54],[12,23,43,54,66],[77,45,23,12,43]])

In [12]:
m

array([[123,  12,  23,  34,  54],
       [ 12,  23,  43,  54,  66],
       [ 77,  45,  23,  12,  43]])

In [1]:
import cv2

In [10]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
cv2.imwrite("newsmallgrey.png", im_g)

True

In [16]:
im_g[2, 2:4]

array([255,  97], dtype=uint8)

In [18]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [21]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [24]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
import numpy

In [27]:
ims = numpy.hstack((im_g, im_g))

In [28]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [33]:
lst = numpy.vsplit(ims, 3)

In [34]:
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]